name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        configuration: [Release, Debug]
        dotnet-version: [3.1.20, 5.0.11]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies on ${{ matrix.dotnet-version }}
      run: dotnet restore
    - name: Build for ${{ matrix.configuration }}
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
